services:
  zoneamento-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8040"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./outputs:/app/outputs
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8040"]
